### ISSUE TITLE
parameter changes at the DistributionMaker level are not populated to all pipelines 

### ISSUE THREAD

**Issue by bourdeet** [IceCubeOpenSource/pisa#648] opened 2020-12-04 17:46 UTC
Attempting to change a hypersurface systematic twice with the same distribution maker leads to a conflict error.
```
import os, sys 
import copy
from collections import OrderedDict

from pisa.core.distribution_maker import DistributionMaker
from pisa.utils.config_parser import parse_pipeline_config
from pisa.core.param import Param, ParamSet



pipeline_neutrinos = os.environ['FRIDGE_DIR'] + '/analysis/oscNext_std_osc/settings/pipeline/pipeline_oscNext_neutrinos_std_osc.cfg'
pipeline_muons = os.environ['FRIDGE_DIR'] + '/analysis/oscNext_std_osc/settings/pipeline/pipeline_oscNext_muons.cfg'

parsed_nu_config = parse_pipeline_config(pipeline_neutrinos)
parsed_mu_config = parse_pipeline_config(pipeline_muons)
MC_template = DistributionMaker([parsed_nu_config, parsed_mu_config])
MC_template.params['dom_eff'].value = 0.94

print('dom eff value: ', MC_template.params['dom_eff'].value )


MC_template.params['dom_eff'].value = 0.84

print('dom eff value now: ', MC_template.params['dom_eff'].value )`
```

Note that the same code works fine when trying to do the same thing on a continuous systematic parameter such as`dis_csms`

**Comment by philippeller** [comment] 2020-12-04 18:17
Hi,

I think the issue is when changing the param it only is actually changed in one pipeline, not both.
Next time you try to access (for example here in your second change), it complains.

The reason that `dis_csms` works, is that it is only in one pipeline, not both.

**Comment by bourdeet** [comment] 2020-12-04 19:45
I see, I guess I can't see this effect because none of the continuous parameters are shared between pipelines...

Is there a workaround possible with another function of DistributionMaker? Or am I forced to change this at the config level?

**Comment by bourdeet** [comment] 2020-12-04 19:52
ok, I can answer my own question:

```
old_param = copy.deepcopy(MC_template.params[pname])
old_param.value = 0.82
MC_template.update_params(params = ParamSet([old_param]))
```

**Comment by philippeller** [comment] 2020-12-07 08:43
This is actually a duplicate of #566

**Comment by philippeller** [comment] 2020-12-07 17:06
I now fixed this behaviour in pisa4

**Closed by philippeller** 2020-12-07 17:06 UTC
